// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _21GoatBackend.Models;

namespace _21GoatBackend.Migrations
{
    [DbContext(typeof(GoatContext))]
    [Migration("20200328142716_Goat")]
    partial class Goat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("_21GoatBackend.Models.Statement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Statements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Erstes Statement",
                            Language = "DE"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
